# The name of the workflow
name: unit-test
# Triggers this workflow on push and on pull request events only for the master branch
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm start
      - run: npm test

  unix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm start
      - run: npm test

  mac-os:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm start
      - run: npm test
